### ISSUE TITLE
Consider using separate elements instead of the `mode` attribute

### ISSUE THREAD

**Issue by zcorpan** [WICG/fenced-frame#30]
This was discussed in the BlinkOn 16 session for fenced frames, where I asked why `iframe` was not reused. @domfarolino said that the mutability of attributes makes things more complex (please correct if I got the point wrong), and further said that maybe separate elements instead of `<fencedframe mode=...>` could make sense to ensure there's no mutation of the mode for the lifetime of the element.

I didn't see an existing issue for this, so filed this one.

**Comment by domfarolino** [comment]
Thanks a lot for filing. Yes overloading `<iframe>` element wasn't super desirable and introducing a new element was relatively cheap. Going further in that same direction, the fact that the `mode` attribute is effectively immutable makes it a little odd that we are using `<fencedframe mode=opaque-ads|read-only|unpartitioned-storage>` instead of an element for each mode (`<opaque-ad>`, etc).

This point was originally raised by @domenic who drew upon the precedent for `<audio>` and `<video>`, instead of `<media mode=audio></media>`, `<media mode=video></media>`, or even more extreme:

```
<element mode=div></element>
<element mode=p></element>
<element mode=ol></element>
<element mode=script></element>
```

An element per mode seems to make sense, but one argument against it is that even though the modes are indeed distinct and immutable throughout a frame's lifetime, the baseline isolation that the fenced frame concept offers is the same—that is, they share a lot of underlying architecture. Though this is very similar to the fact that HTMLAudioElement and HTMLVideoElement both implement the abstract HTMLMediaElement interface, so I guess we could have an HTMLFencedFrameElement interface that HTMLOpaqueAdElement and friends implement...

In any case, it would be great to hear opinions from more vendors and HTML experts

**Comment by domfarolino** [comment]
javascript: URLs will not be accepted; they require the target frame to be synchronously scriptable, which is a guarantee that cannot be made with a fenced frame, since it will live in a separate browsing context group. The other reason is that we explicitly disallow them.

While the exact URL restrictions are not yet in the spec (soon!) they are described in https://github.com/WICG/fenced-frame/blob/master/explainer/modes.md. Currently we only allow https, localhost, about:blank. Except for the opaque-ads mode, where we also allow opaque `urn:uuid` URLs.

**Comment by domfarolino** [comment]
We've ultimately landed on not going with separate elements, and actually eliminating the `mode` attribute altogether in favor of the more configurable `FencedFrameConfig` object (https://github.com/WICG/fenced-frame/blob/master/explainer/fenced_frame_config.md), which we presented at TPAC. Given that and the discussion we had there, I think we can close this now.
