### ISSUE TITLE
Need to split the feature to individual primitives and figure out the best ways to support them

### ISSUE THREAD

**Issue by smaug----** [WICG/fenced-frame#50]
The proposal would add yet another sandbox-type of (i)frame, similarly to [anonymous iframe](https://wicg.github.io/anonymous-iframe/).
There are already way too many ways how the behavior of an (i)frame can be controlled, so it would be better to think of coherent way to do it all and not add more and more ways.
I'd start by listing somewhere all the ways the behavior can be currently tweaked, and which behavior exactly and how the new proposals work with all the existing stuff.

(I'm not yet sure whether the platform should have the features Fenced Frame would add, partially because the proposal seems to be still very unclear on many things)

**Comment by domfarolino** [comment]
Thanks for the feedback! I think one reason we went with a different element is that the overall isolation and processing model is fundamentally different enough to warrant it (this was the advice we got from a couple of HTML editors), and the fact that we can't really add more things to `sandbox` since that wouldn't be backwards-compatible. I'm open to more ideas as to how we can converge things more if it is possible though.

> (I'm not yet sure whether the platform should have the features Fenced Frame would add, partially because the proposal seems to be still very unclear on many things)

Could you list some specific things that the proposal isn't very clear on?

**Comment by smaug----** [comment]
> Could you list some specific things that the proposal isn't very clear on?

Session history for example

**Comment by shivanigithub** [comment]
> 
> Session history for example

Here's the description for [session history behavior](https://github.com/WICG/fenced-frame/blob/master/explainer/integration_with_web_platform.md#session-history). Hope this clarifies.

**Comment by domfarolino** [comment]
Given the inactivity here, and the progress on the spec and overhaul of API changes, I think the overall processing model and integration with many web platform features is a good deal more clear these days. Absent a concrete action item from this issue I'll close this. If you have more feedback we'd love to hear it (note that we've filed https://github.com/mozilla/standards-positions/issues/781 as well).
